# Generated by Django 4.0.3 on 2022-03-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_bost_cost_delete_most_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='ma',
        ),
    ]
