# Generated by Django 4.0.3 on 2022-03-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_most_post_image_post_is_deleted'),
        ('pay', '0003_remove_cost_ma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bost',
            name='ma',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='post.post'),
        ),
    ]
